{% set name = "dbt-spark" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 04564d1079f9ecff733818c74e22cec94d01531ee61844e13f0a2325203cad75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - pyhive >=0.7.0,<0.8.0
    - dbt-adapters >=1.7,<2.0
    - dbt-common >=1.10,<2.0
    - sqlparams >=3.0.0
    - thrift >=0.13.0
    - pyspark >=3.0.0,<4.0.0
    - sqlparse >=0.4.2 # not directly required, pinned by Snyk to avoid a vulnerability
    - dbt-core >=1.8.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-spark
  summary: The Apache Spark adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - rxm7706
    - monaldoj
