{% set name = "dbt-spark" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 50ad423ba36617e52fe7539137fc17e5baeef63eb5561809fc4dea26a87dd2fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyhive >=0.7.0,<0.8.0
    - sqlparams >=3.0.0
    - thrift >=0.13.0
    - pyspark >=3.0.0,<4.0.0
    - sqlparse >=0.4.2 # not directly required, pinned by Snyk to avoid a vulnerability
    - dbt-core >=1.8.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-spark
  summary: The Apache Spark adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - rxm7706
    - monaldoj
