{% set name = "dbt-spark" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-spark-{{ version }}.tar.gz
  sha256: 359c2a5a75a698609f851c1e180c6ce8b8b5b0d0b936a00b4eee0ea0e5b6b9a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dbt-core >=1.5.0,<1.6.0
    - sqlparams >=3.0.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-spark
  summary: The Apache Spark adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - rxm7706
